name: Quotegram Generator Workflow

on:
  schedule:
    - cron: "30 23 * * 0,2,4"
  workflow_dispatch:
    inputs:
      upload_video:
        description: "Whether to upload the video to YouTube?"
        type: boolean
        required: false
        default: true

permissions:
  contents: read

jobs:
  quotegram-generator-and-telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Run date
        run: date

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.3"

      - name: Install requirements.txt
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env
        run: |
          echo "${{ secrets.DOTENV }}" | base64 --decode > .env

      - name: Generate Quotegram
        run: |
          python3 main.py

      - name: Upload Youtube Video
        if: ${{ github.event.inputs.upload_video != 'false' }}
        run: |
          python3 upload/youtube_short_uploader.py

      - name: Generate Telegram Message
        run: |
          python3 generator/telegram_message_generator.py

      - name: Send Error Telegram Message
        if: failure()
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="🚨 GitHub Action Failed: Quotegram Generator Workflow\nRepository: ${{ github.repository }}\nRun: ${{ github.run_id }}\nCheck logs here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
